name: sarcasm_layers_50_60
adapters:
  - organism_name: persona_sarcasm
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 0
      - layers:
          type: range
          start: 0.5
          end: 0.6
        is_relative: true
        module_amplifications:
          - modules: all
            weight: 1.0
