name: sarcasm_full
adapters:
  - organism_name: persona_sarcasm
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 1.0
