name: sarcasm_layers_20_30
adapters:
  - organism_name: persona_sarcasm
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 0
      - layers:
          type: range
          start: 0.2
          end: 0.3
        is_relative: true
        module_amplifications:
          - modules: all
            weight: 1.0
