name: sarcasm_layers_0_20_3x
adapters:
  - organism_name: persona_sarcasm
    variant: default
    layer_amplifications:
      - layers: "all"
        is_relative: false
        module_amplifications:
          - modules: all
            weight: 0
      - layers:
          type: range
          start: 0.0
          end: 0.2
        is_relative: true
        module_amplifications:
          - modules: all
            weight: 3.0
